### PR TITLE
Tasks completed by Fatimah Akanbi

### PR DESCRIPTION
**Pull request by akanbifatimah**
Completed Tasks 
Task0

### CODE REVIEW

**Comment by akanbifatimah** [comment]
@jafsia @Fadanka Kindly Review, Please.

**Comment by Fadanka** [comment]
Dear Fatimah. Thank you for your great contributions. Completion of task 0 really showed a high level of mastery of GitHub. Your brilliant contribution to task 1 is also very impressive; The blog and content are well-structured and easy to follow. Amazing contributions well done!

**Comment by akanbifatimah** [comment]
> Dear Fatimah. Thank you for your great contributions. Completion of task 0 really showed a high level of mastery of GitHub. Your brilliant contribution to task 1 is also very impressive; The blog and content are well-structured and easy to follow. Amazing contributions well done!

Thank you so much for your kind words sir, happy to contribute.

**Comment by jafsia** [comment]
Happy to see how you have mastered Github. Your documentation seems very exhaustive. Nice work.

**Comment by akanbifatimah** [comment]
> Happy to see how you have mastered Github. Your documentation seems very exhaustive. Nice work.

Thank you for your kind words sir.

**Pull request merged**
