### PR TITLE
Added Task0.md

### PR DESCRIPTION
**Pull request by FadlullahLanre**
### Submission of Task-0

Added a folder named December-March-Contributions
Created a folder with my name [Abdussalam Fadlullah]
Added a file named Task0.md and added a list of completed activities

### CODE REVIEW

**Comment by FadlullahLanre** [comment]
Compiled information about typhoid fever.
Created and designed text content based on collected informations.

**Comment by FadlullahLanre** [comment]
Completed Task 2
Created a technical documentation that contains proposed changes and tools to be used

**Comment by jafsia** [comment]
The technical specifications you propose seem sensible but you do not specify the method you will use. Moreover, pictures speak louder than words. A visual overview would be welcome.

**Comment by FadlullahLanre** [comment]
@jafsia Thank you Sir, i'll make amendments to the documentation.

**Pull request merged**
