### PR TITLE
Harrison

### PR DESCRIPTION
**Pull request by Ogalo**
@Fadanka @jafsia kindly review task 1.

### CODE REVIEW

**Comment by Ogalo** [comment]
@Fadanka @jafsia Added a contribution, Kindly review it.

**Comment by Ogalo** [comment]
Added the steps for the development of the blog content web. Kindly review it @Fadanka @jafsia

**Comment by Fadanka** [comment]
Dear Ogalo, Thanks so much for this amazing and complete contribution. I like the idea of using react for the block post, it is open source and has great potential for Building fast and interactive user interfaces which will be useful to have in the app. Nice idea to try bringing an interactive environment to create content for the blog. I assume you already thought about adding more components to make the interface even more complete. Thanks for the step-by-step development, looks really good.

**Comment by jafsia** [comment]
Your branch has conflict files please resolve the issue.

**Comment by Ogalo** [comment]
On it am fixing them.

**Comment by Ogalo** [comment]
I don't have write access to resolve the conflicts. Kindly resolve them from your end Thanks. @jafsia 

WhatsApp Image 2022-11-01 at 19 51 13

**Pull request closed without merging**
